# User config
author: 'Home page'
description:  "Python, Fortran, Biogeochemistry, Oceanography, Data vizualisaton,Data analysis"
tagline: 'test'
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "myemail@example.com"
#linkedin: "https://www.linkedin.com/"
#twitter: "https://twitter.com/"
Github: "https://github.com/lisapro"
Researchgate: "https://www.researchgate.net/profile/Elizaveta_Protsenko2"
# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
